[package]
name = "otama"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[dependencies]
otama-sys = { version = "0.1", path = "otama-sys" }
glob = "0.2"

[build-dependencies]
bindgen = "0.23"
